In [113]:
# import packages
import pandas as pd
import numpy as np

#Import dataset
education = pd.read_csv('C:\\Users\\mboke\\Documents\\2020\\Summer II\\Tech Bootcamp\\Education.csv')

In [114]:
# Displaying dataframe attributes
nrows, ncols = education.shape
nrows, ncols

(400277, 26)

In [115]:
# Explore an observation
education.iloc[3]

Unnamed: 0                                        364634
Function                         Substitute Compensation
Use                                          Instruction
Sharing                                  School Reported
Reporting                                         School
Student_Type                                 Unspecified
Position_Type                                 Substitute
Object_Type                                     Benefits
Pre_K                                           NO_LABEL
Operating_Status                       PreK-12 Operating
Object_Description                     EMPLOYEE BENEFITS
Text_2                                      TEACHER SUBS
SubFund_Description                         GENERAL FUND
Job_Title_Description           Teacher, Short Term Sub 
Text_3                                           Regular
Text_4                                               NaN
Sub_Object_Description                               NaN
Location_Description           

In [99]:
# Start acquiring information about the data
# use head to view the first 10 rows
education.head(10)

Unnamed: 0                            Function          Use  \
0      134338                Teacher Compensation  Instruction   
1      206341                            NO_LABEL     NO_LABEL   
2      326408                Teacher Compensation  Instruction   
3      364634             Substitute Compensation  Instruction   
4       47683             Substitute Compensation  Instruction   
5      229958            Facilities & Maintenance          O&M   
6      417668  Instructional Materials & Supplies  Instruction   
7      126378                       Food Services          O&M   
8      275539                Teacher Compensation  Instruction   
9       85262             Substitute Compensation  Instruction   

                     Sharing   Reporting       Student_Type  \
0            School Reported      School           NO_LABEL   
1                   NO_LABEL    NO_LABEL           NO_LABEL   
2            School Reported      School        Unspecified   
3            School Reported      School        Unspecified   
4            School Reported      School        Unspecified   
5            School Reported      School        Unspecified   
6            School Reported      School  Special Education   
7  School on Central Budgets  Non-School        Unspecified   
8            School Reported      School        Unspecified   
9            School Reported      School        Unspecified   

         Position_Type               Object_Type     Pre_K   Operating_Status  \
0              Teacher                  NO_LABEL  NO_LABEL  PreK-12 Operating   
1             NO_LABEL                  NO_LABEL  NO_LABEL      Non-Operating   
2              Teacher  Base Salary/Compensation  Non PreK  PreK-12 Operating   
3           Substitute                  Benefits  NO_LABEL  PreK-12 Operating   
4              Teacher   Substitute Compensation  NO_LABEL  PreK-12 Operating   
5            Custodian                  Benefits  NO_LABEL  PreK-12 Operating   
6         Non-Position        Supplies/Materials  NO_LABEL  PreK-12 Operating   
7  Coordinator/Manager                  Benefits  NO_LABEL  PreK-12 Operating   
8              Teacher                  Benefits  NO_LABEL  PreK-12 Operating   
9           Substitute                  Benefits  NO_LABEL  PreK-12 Operating   

   ... Sub_Object_Description            Location_Description  FTE  \
0  ...                    NaN                             NaN  1.0   
1  ...                    NaN                             NaN  NaN   
2  ...                    NaN                             NaN  1.0   
3  ...                    NaN                             NaN  NaN   
4  ...                    NaN                             NaN  NaN   
5  ...                    NaN                             NaN  NaN   
6  ...                    NaN                             NaN  NaN   
7  ...                    NaN  DISTRICT WIDE ORGANIZATION UNI  NaN   
8  ...                    NaN                             NaN  NaN   
9  ...                    NaN                             NaN  NaN   

            Function_Description Facility_or_Department  \
0                            NaN                    NaN   
1                       RGN  GOB                    NaN   
2                            NaN                    NaN   
3        UNALLOC BUDGETS/SCHOOLS                    NaN   
4                    NON-PROJECT                    NaN   
5                    NON-PROJECT                    NaN   
6                            NaN                    NaN   
7                    NON-PROJECT                    NaN   
8  ELA S - TEACHING SPANISH ONLY                    NaN   
9        UNALLOC BUDGETS/SCHOOLS                    NaN   

               Position_Extra      Total             Program_Description  \
0               KINDERGARTEN   50471.810                    KINDERGARTEN   
1                UNDESIGNATED   3477.860   BUILDING IMPROVEMENT SERVICES   
2                     TEACHER  62237.130 

In [75]:
# Use describe to get summary statistics
education.describe()

Unnamed: 0            FTE         Total
count  400277.000000  126071.000000  3.957220e+05
mean   225186.018537       0.426794  1.310586e+04
std    130025.142718       0.573576  3.682254e+05
min         2.000000      -0.087551 -8.746631e+07
25%    112601.000000       0.000792  7.379770e+01
50%    225243.000000       0.130927  4.612300e+02
75%    337722.000000       1.000000  3.652662e+03
max    450340.000000      46.800000  1.297000e+08

In [116]:
# Drop "Unnamed: 0", we can use the auto-generated index instead
education.drop(columns="Unnamed: 0", inplace=True)

In [117]:
# Observe the column names
for name in education.columns:
    print(name)

Function
Use
Sharing
Reporting
Student_Type
Position_Type
Object_Type
Pre_K
Operating_Status
Object_Description
Text_2
SubFund_Description
Job_Title_Description
Text_3
Text_4
Sub_Object_Description
Location_Description
FTE
Function_Description
Facility_or_Department
Position_Extra
Total
Program_Description
Fund_Description
Text_1


In [118]:
# Find the number of NA values per column
pd.isnull(education).sum()

Function                       0
Use                            0
Sharing                        0
Reporting                      0
Student_Type                   0
Position_Type                  0
Object_Type                    0
Pre_K                          0
Operating_Status               0
Object_Description         24784
Text_2                    312060
SubFund_Description        93422
Job_Title_Description     107534
Text_3                    291125
Text_4                    346531
Sub_Object_Description    308674
Location_Description      238223
FTE                       274206
Function_Description       58082
Facility_or_Department    346391
Position_Extra            135513
Total                       4555
Program_Description        95617
Fund_Description          197400
Text_1                    107992
dtype: int64

In [119]:
# Check for duplicated rows
education.duplicated().sum()

17650

In [120]:
# Drop duplicate rows 
education.drop_duplicates(inplace=True)

In [121]:
# Double check that the duplicates were removed
education.duplicated().sum()

0

In [82]:
# Find the data types of each column
education.dtypes

Function                   object
Use                        object
Sharing                    object
Reporting                  object
Student_Type               object
Position_Type              object
Object_Type                object
Pre_K                      object
Operating_Status           object
Object_Description         object
Text_2                     object
SubFund_Description        object
Job_Title_Description      object
Text_3                     object
Text_4                     object
Sub_Object_Description     object
Location_Description       object
FTE                       float64
Function_Description       object
Facility_or_Department     object
Position_Extra             object
Total                     float64
Program_Description        object
Fund_Description           object
Text_1                     object
dtype: object

In [122]:
# Find number of unique values in each column
education.nunique(dropna=False)

Function                      37
Use                            8
Sharing                        5
Reporting                      3
Student_Type                   9
Position_Type                 25
Object_Type                   11
Pre_K                          3
Operating_Status               3
Object_Description           603
Text_2                       302
SubFund_Description          275
Job_Title_Description       3517
Text_3                        35
Text_4                       245
Sub_Object_Description       183
Location_Description         355
FTE                        21004
Function_Description         688
Facility_or_Department       180
Position_Extra               581
Total                     286495
Program_Description          422
Fund_Description             142
Text_1                      1424
dtype: int64

After closely reading the problem statement on driven data, I came to understand that the columns "Function" through "Operating Status" each contain a label.  The remaining columns are all freform text data (aside from FTE and Total, which are freeform float values).

Although the columns containing a label sometimes contain "NO LABEL," we decided that we didn't want to drop these rows or replace "NO LABEL" with NA. The "NO LABEL" gives us insights that the label didn't fall into one of the other categories listed.

In [84]:
# Figure out what Text_1, Text_2, Text_3, Text_4 contain
education["Text_2"].unique()

array([nan, 'BOND EXPENDITURES', 'TEACHER SUBS',
       'SPECIAL EDUCATION INSTRUCTION', 'ADM/PROF',
       'OPERATIONS - UTILITIES', 'TEACHER', 'FOOD SERVICES',
       'CITY WIDE MUSIC GROUPS', 'CUSTODIAL SERVICES',
       'UNASSIGNED PERS/PAID LEAVES', 'ESL/BILINGUAL EDUCATION',
       'POST SECONDARY READINESS', 'TRANSPORTATION',
       'SCHOOL NURSE SERVICES', 'SUPPLIES & MATERIALS',
       'INSTRUCTIONAL SUPPORT TEAMS', 'SPECIAL ED SYSTEMWIDE COSTS',
       'ATHLETICS', 'SCHOOL ADMINISTRATIVE SUPPORT', 'GENERAL EDUCATION',
       'TIF GRANT', 'PREVENTION AND INTERVENTION', 'CUSTODIAL-SCHOOLS',
       'TEACHER LEARNING & LEADERSHIP', 'MAINTENANCE',
       'PERSONNEL SERVICES', 'STUDENT SERVICES CHARTER SCHOO',
       'TRANSPORT', 'AFTERSCHOOL PROGRAMS', 'EARLY EDUCATION',
       'LEGAL SERVICES', 'PROFESSIONAL DEVELOPMENT PROGRAMS',
       'PUBLIC UTILITIES', 'ADULT VOC ED OPPORTUNITY',
       'SAFETY AND SECURITY', 'PRINCIPAL', 'LIBRARY & MEDIA',
       'GRANTS MANAGEMENT', 'WAREH

In [44]:
education["Text_3"].unique()

array([nan, 'Regular', 'Alternative', 'Turnaround',
       'Professional and Contract Services', 'New/Closed Schl', 'Charter',
       'Other Services', 'Employee Travel', 'Supplies for Instruction',
       'Communication and IT Related', 'Insurance Related Expenses',
       'Staff Development', 'Equipment for Operations',
       'Other Materials and Supplies', 'Allocations to Schools',
       'Compass Learning', 'Transportation', 'Textbooks', 'Other',
       'Autism Partnership', 'Rent', 'Indirect Costs',
       'Equipment for Instruction', 'Periodicals, Office supplies Etc',
       'Liability Charges', "Trustee's Commissions", 'ITEMFH',
       'Workers Compensation Charges',
       'Dues / Memberships Not in Registrations', 'Debt Transfers',
       'Distinguished Professionals of ITEMFC', 'Project GRAD ofITEMFC',
       'Other Services Misc', 'Voyager Expanded Learning'], dtype=object)

In [85]:
education["Text_1"].unique()

array([nan, 'BUILDING IMPROVEMENT SERVICES', 'REGULAR INSTRUCTION', ...,
       'FAM & COMM EMPOWER CONF', 'NC NEW SCHOOLS PROJ - ',
       'MEMORIAL FUND'], dtype=object)

In [86]:
education["Text_4"].unique()

array([nan, 'Regular Instruction', 'SIG - ARRA',
       'Transportation - Bus Drivers', 'Title I - Supervisors',
       'Undistributed', 'Operation of Plant',
       'Basic Educational Services - District Objective ', 'All Sports',
       'First Class', 'Special Education Instruction',
       'Printers for teachers and therapists', 'Title I - Teachers',
       'Regular Salary', 'transportation - Second Runs', 'IDEA Part B  ',
       'Regular Instructional Support', 'Teacher Induction',
       'Office of Principal', 'IAF', 'Education Jobs Program',
       'Teacher Advancement Program (TAP)',
       'Computers for instruction purposes for students w/ disabilit',
       'Held Funds', 'Parent Literacy', 'choir', 'External Vendor',
       'Other Student Support', 'Summer School',
       'Special Education Support', 'Extended Week',
       'RTTP Focus Schools ', 'Extra Duty', 'Custodial - Substitutes',
       'transportation - mechanics', 'IDEA Part B',
       'Title II Part A - Highly Quali

In [123]:
# After inspecting Text_ 1-4, it was clear that the information in each of these columns did not fall under
# specific categories and could all be contained in one column

# First, fill na values with ' ' to make addition of columns possible
education[["Text_1","Text_2","Text_3","Text_4"]]= education[["Text_1","Text_2","Text_3","Text_4"]].fillna(' ')
education["Text_1"] = education["Text_1"] + education["Text_2"] + education["Text_3"] + education["Text_1"]

In [124]:
# Check to make sure it worked:
pd.isnull(education["Text_1"]).sum()

0

In [125]:
# Now drop Text_2-4
education.drop(columns=["Text_2","Text_3","Text_4"],inplace=True)

In [126]:
# To deal with NA values, we can impute by utilizing the most common value for each column

# build a function to generate most common value for a given column:
def most_frequent(column_name):
    # pull all values for that label in function and the column for which we want to find the most frequent value
    all_values = education[column_name]
    # initialize dictionary
    counter = {}
    # fill dictionary with key value pairs to find the most common entry
    for word in all_values:
        if not pd.isnull(word):
            if word in counter:
                counter[word]+=1
            else:
                counter[word]=1
    Keymax = max(counter, key=counter.get)
    # return entry that appeared most frequently
    return Keymax

In [127]:
# initialize dictionary to state most frequent value per column
frequent_dict = {}

# Create list of freeform text columns
freeform_columns = education.columns[9:]

# Populate the dictionary
for col in freeform_columns:
    frequent_dict[col] = most_frequent(col)

In [128]:
#Check the frequent_dict to make sure it worked:
frequent_dict

{'Object_Description': 'EMPLOYEE BENEFITS',
 'SubFund_Description': 'GENERAL FUND',
 'Job_Title_Description': 'Teacher, Elementary ',
 'Sub_Object_Description': 'Extra Duty Pay/Overtime For Support Personnel',
 'Location_Description': 'School ',
 'FTE': 1.0,
 'Function_Description': 'NON-PROJECT',
 'Facility_or_Department': 'All Campus Payroll',
 'Position_Extra': 'PROFESSIONAL-INSTRUCTIONAL',
 'Total': 0.22,
 'Program_Description': 'EMPLOYEE BENEFITS',
 'Fund_Description': 'General Operating Fund',
 'Text_1': '    '}

In [129]:
# Now impute using fillna:
education.fillna(value=frequent_dict,inplace=True)

In [130]:
# double check that all NA values have been replaced
pd.isnull(education).sum()

Function                  0
Use                       0
Sharing                   0
Reporting                 0
Student_Type              0
Position_Type             0
Object_Type               0
Pre_K                     0
Operating_Status          0
Object_Description        0
SubFund_Description       0
Job_Title_Description     0
Sub_Object_Description    0
Location_Description      0
FTE                       0
Function_Description      0
Facility_or_Department    0
Position_Extra            0
Total                     0
Program_Description       0
Fund_Description          0
Text_1                    0
dtype: int64

In [131]:
# write output to cleaned CSV
education.to_csv(path_or_buf = 'C:\\Users\\mboke\\Documents\\2020\\Summer II\\Tech Bootcamp\\CleanedEducation.csv')